# Generated by Django 4.2.16 on 2024-09-18 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vector_search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.CharField(default=vector_search.models.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VectorDatabase',
            fields=[
                ('project_id', models.CharField(default=vector_search.models.short_uuid, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('index_file', models.FileField(upload_to='vector_dbs/')),
                ('chunks_file', models.FileField(upload_to='vector_dbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(related_name='vector_databases', to='vector_search.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='vector_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vector_search.vectordatabase'),
        ),
    ]
